server:
  port: 8081

topic:
  name: t.food.order

spring:
  kafka:
    consumer:
      group-id: "default"
    # надо для указания сервера, где крутится kafka
    bootstrap-servers: 192.168.0.110:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    password: 1234qwer
    username: postgres
  jpa:
    generate-ddl: true